### ISSUE TITLE
Install tango on the VM from the source distribution

### ISSUE THREAD

**Issue by piogor** [tango-controls/tangobox#15]
Follow: https://github.com/tango-controls/TangoSourceDistribution/blob/master/README.md
- [x] build the source distribution package
- [x] install the alfa version it on the VM directly, with --prefix=/usr/local, include db and access control 
- [x] install services
- [x] manually check with tango test 
- [x] copy the source .tar.gz file to ~/work/tangobox/build
- [x] prepare script which will automate this for future automate VM creation

Please note that the databaseds service is running on the VM temporally and will be moved to a container, later.

**Comment by Ingvord** [comment]
@piogor ,

> Follow: https://github.com/tango-controls/TangoSourceDistribution/blob/master/README.md
>   build the source distribution package

my philosophy is that you should not build TangoSourceDistribution  manually. It is done by travis.

I understand you need now a package though. 

@bourtemb , what do you think - can we tag TangoSourceDistribution repo now and call it pre-9.3.2 release? Then @piogor  could just download tar.gz from releases.

**Comment by Ingvord** [comment]
@piogor ,

> install it on the VM directly, with --prefix=/usr/local, include db and access control

FYI you may need this: [How to configure TangoSourceDiswtribution on Ubuntu 18.04LTS](https://github.com/tango-controls/TangoSourceDistribution/wiki#how-to-configure-tangosourcedistribution-on-ubuntu-1804lts)

**Comment by piogor** [comment]
Thanks @Ingvord, an yes I would like to have the source distribution pre-9.3.2. Later I will change the install/make script of tangobox to use the release packages :).

**Comment by Ingvord** [comment]
@piogor let's wait for @bourtemb response, I would also merge [TangoSourceDistribution#13](https://github.com/tango-controls/TangoSourceDistribution/pull/13) before tagging

**Comment by bourtemb** [comment]
I agree with @Ingvord.  https://github.com/tango-controls/TangoSourceDistribution/pull/13 can be merged before tagging.
Then, a tag with a name like 9.3.2-alpha.1 could be created because I guess there might be several pre-release versions.

**Comment by piogor** [comment]
Then I will wait for alpha.1, taking advantage of having the rest-api build in just from the begining :-) (and whatever latest release will be prior to tangobox publication).  However, I already have done successful exercise with building the source distribution package on Ubuntu :).

**Comment by Ingvord** [comment]
@piogor , here is the link: [tango-9.3.2-alpha.1.tar.gz](https://github.com/tango-controls/TangoSourceDistribution/releases/download/9.3.2-alpha.1/tango-9.3.2-alpha.1.tar.gz)

**Comment by piogor** [comment]
@Ingvord and @bourtemb , thanks!
